name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: binbashing/fail2ban-cf-iplist:latest
          platforms: linux/amd64, linux/arm64/v8, linux/arm/v7, linux/i386

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: binbashing/fail2ban-cf-iplist
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    # Use Entepotenz's lightweight keepalive action (creates an empty commit
    # when repo is close to inactive threshold). Requires repo write rights.
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Keep repo alive
        uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
        with:
          TIME_ELAPSED_THRESHOLD_IN_DAYS: '50'